services:
  #================================================================================================
  # Client Gateway Service
  #================================================================================================
  client-gateway:
    build: ./client-gateway
    ports:
      - ${CLIENT_GATEWAY_PORT}:3000
    develop:
      watch:
        - action: sync
          path: ./client-gateway/src
          target: /usr/src/app/src
          ignore:
            - node_modules
    # volumes:
    #   - ./client-gateway/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nast-server:4222

  #================================================================================================
  # NATS Server
  #================================================================================================
  nast-server:
    image: nats:latest
    ports:
      - "8222:8222"

  #================================================================================================
  # Products Microservice
  #================================================================================================
  products-ms:
    build: ./products-ms
    develop:
      watch:
        - action: sync
          path: ./products-ms/src
          target: /usr/src/app/src
          ignore:
            - node_modules
      # volumes:
      #   - ./client-gateway/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3001
      - NATS_SERVERS=nats://nast-server:4222
      - DATABASE_URL=file:./dev.db

  #================================================================================================
  # Orders Microservice
  #================================================================================================
  orders-ms:
    depends_on:
      - orders-db
    build: ./orders-ms
    develop:
      watch:
        - action: sync
          path: ./orders-ms/src
          target: /usr/src/app/src
          ignore:
            - node_modules
      # volumes:
      #   - ./client-gateway/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3002
      - NATS_SERVERS=nats://nast-server:4222
      - DATABASE_URL=postgresql://postgres:123456@orders-db:5432/ordersdb?schema=public

  #================================================================================================
  # Orders Database
  #================================================================================================
  orders-db:
    container_name: orders_database
    image: postgres:16.2
    # restart: always
    volumes:
      - ./orders-ms/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=ordersdb

  #================================================================================================
  # Payment Microservice
  #================================================================================================
  payments-ms:
    container_name: payments-ms
    build: ./payments-ms
    develop:
      watch:
        - action: sync
          path: ./payments-ms/src
          target: /usr/src/app/src
          ignore:
            - node_modules
      # volumes:
      #   - ./client-gateway/src:/usr/src/app/src
    command: npm run start:dev
    ports:
      - ${PAYMENTS_MS_PORT}:${PAYMENTS_MS_PORT}
    environment:
      - PORT=${PAYMENTS_MS_PORT}
      - NATS_SERVERS=nats://nast-server:4222
      - STRIPE_SECRET=${STRIPE_SECRET}
      - STRIPE_SUCCESS_URL=${STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${STRIPE_CANCEL_URL}
      - STRIPE_ENDPOINT_SECRET=${STRIPE_ENDPOINT_SECRET}
